// all 6 scenario definitions
// ported from attack_engine.py SCENARIOS dict

import type { ScenarioConfig, Alert, AttackPhase } from './types';

// helper to make alert objects less verbose
function makeAlert(
  id: string,
  severity: Alert['severity'],
  type: Alert['type'],
  title: string,
  sourceIp: string,
  targetNodeId: string,
  desc: string,
  isFP: boolean,
  evidence: string,
  mitreId: string,
  confidence: number,
): Alert {
  return {
    alertId: id,
    severity,
    type,
    title,
    sourceIp,
    targetNodeId,
    description: desc,
    timestamp: 0,
    status: 'new',
    isFalsePositive: isFP,
    forensicEvidence: evidence,
    mitreId,
    confidence,
  };
}

function makePhase(
  id: string,
  name: string,
  desc: string,
  target: string,
  type: AttackPhase['attackType'],
  steps: number,
  mitreId: string,
  mitreName: string,
  tactic: string,
  sourceIp: string,
  effect: AttackPhase['compromiseEffect'] = 'compromised',
): AttackPhase {
  return {
    phaseId: id,
    name,
    description: desc,
    targetNodeId: target,
    attackType: type,
    stepsToComplete: steps,
    stepsElapsed: 0,
    isActive: true,
    isNeutralized: false,
    mitreId,
    mitreName,
    mitreTactic: tactic,
    compromiseEffect: effect,
    sourceIp,
  };
}

export const SCENARIOS: Record<string, ScenarioConfig> = {
  script_kiddie: {
    id: 'script_kiddie',
    name: 'Script Kiddie Brute Force',
    description:
      'A script kiddie is running an SSH brute force attack against web-01 from IP 185.220.101.42. Investigate alerts, block the attacker, secure the server.',
    difficulty: 'easy',
    maxSteps: 15,
    adversaryBehavior: 'static',
    mitreTechniques: ['T1110.001'],
    threatCount: 1,
    falsePositiveCount: 1,
    initialCompromisedNodes: [],
    attackPhases: [
      makePhase(
        'bf-01', 'SSH Brute Force', 'Automated SSH login attempts against web-01',
        'web-01', 'brute_force', 8, 'T1110.001',
        'Brute Force: Password Guessing', 'credential-access',
        '185.220.101.42',
      ),
    ],
    alerts: [
      makeAlert(
        'ALT-0001', 'high', 'brute_force',
        'Multiple Failed SSH Logins',
        '185.220.101.42', 'web-01',
        'Over 500 failed SSH login attempts detected from external IP.',
        false,
        'SSH brute force attack detected. Source: 185.220.101.42. 847 failed attempts in 10 minutes targeting root, admin, deploy accounts. Known Tor exit node.',
        'T1110.001', 0.95,
      ),
      makeAlert(
        'ALT-0002', 'medium', 'anomalous_traffic',
        'Unusual Outbound Traffic',
        '10.0.2.1', 'web-01',
        'Spike in outbound connections from web-01.',
        false,
        'Outbound connection spike correlates with brute force timing. Possible C2 callback attempt if credentials were compromised. Monitor closely.',
        'T1110.001', 0.8,
      ),
      makeAlert(
        'ALT-0003', 'low', 'anomalous_traffic',
        'Scheduled Backup Traffic',
        '10.0.3.3', 'backup-01',
        'Large data transfer detected from backup server.',
        true,
        'Benign activity. Routine nightly backup job to offsite storage. Matches expected schedule and data volume. No indicators of compromise.',
        '', 0.15,
      ),
    ],
    falsePositiveAlerts: [],
  },

  phishing_campaign: {
    id: 'phishing_campaign',
    name: 'Phishing Campaign Triage',
    description:
      'Targeted phishing hit the org. 5 alerts fired — 3 real malware infections on workstations, 2 false positives from legitimate email. Quarantine infected hosts, dismiss FPs.',
    difficulty: 'medium',
    maxSteps: 25,
    adversaryBehavior: 'evasive',
    mitreTechniques: ['T1566.001', 'T1204.002', 'T1021.002'],
    threatCount: 3,
    falsePositiveCount: 2,
    initialCompromisedNodes: [],
    attackPhases: [
      makePhase(
        'phish-01', 'Malware Infection ws-01',
        'Workstation ws-01 opened phishing attachment, malware installed',
        'ws-01', 'phishing', 6, 'T1566.001',
        'Phishing: Spearphishing Attachment', 'initial-access',
        '94.232.46.19',
      ),
      makePhase(
        'phish-02', 'Malware Infection ws-02',
        'Workstation ws-02 opened phishing attachment, malware installed',
        'ws-02', 'phishing', 6, 'T1204.002',
        'User Execution: Malicious File', 'execution',
        '94.232.46.19',
      ),
      makePhase(
        'phish-03', 'Lateral Movement to app-01',
        'Malware spreading from ws-01 to app-01 via SMB',
        'app-01', 'lateral_movement', 10, 'T1021.002',
        'SMB/Windows Admin Shares', 'lateral-movement',
        '10.0.4.1',
      ),
    ],
    alerts: [
      makeAlert(
        'ALT-0001', 'critical', 'phishing',
        'Spearphishing Attachment Opened',
        '94.232.46.19', 'ws-01',
        'User on ws-01 opened malicious email attachment.',
        false,
        'Malicious macro executed from document "Invoice_Q4.docm". Dropped payload to %TEMP%. Established reverse shell to 94.232.46.19:4444. Cobalt Strike beacon detected.',
        'T1566.001', 0.98,
      ),
      makeAlert(
        'ALT-0002', 'high', 'malware',
        'Suspicious Process Execution',
        '10.0.4.2', 'ws-02',
        'Unknown process spawned from email client on ws-02.',
        false,
        'Process "svchost_update.exe" spawned from Outlook.exe. Writing to HKLM\\Run for persistence. Connecting to 94.232.46.19 on port 8443. Malicious.',
        'T1204.002', 0.92,
      ),
      makeAlert(
        'ALT-0003', 'medium', 'lateral_movement',
        'SMB Connection Attempt',
        '10.0.4.1', 'app-01',
        'ws-01 attempting SMB connections to app-01.',
        false,
        'Unauthorized SMB session from ws-01 to app-01 using compromised domain credentials. Attempting to copy payload via admin share. Lateral movement in progress.',
        'T1021.002', 0.85,
      ),
      makeAlert(
        'ALT-0004', 'low', 'anomalous_traffic',
        'Email Server Health Check',
        '10.0.2.2', 'mail-01',
        'Automated health check traffic from monitoring system.',
        true,
        'Benign. Nagios health check polling mail-01 SMTP/IMAP ports. Matches expected monitoring schedule. Source is internal Nagios server 10.0.1.50.',
        '', 0.12,
      ),
      makeAlert(
        'ALT-0005', 'low', 'anomalous_traffic',
        'Cron Job Network Activity',
        '10.0.3.2', 'app-01',
        'Scheduled task generating network traffic.',
        true,
        'Benign. Routine cron job on app-01 pulling config updates from internal git repo. Expected behavior per deployment pipeline documentation.',
        '', 0.1,
      ),
    ],
    falsePositiveAlerts: [],
  },

  apt_lateral_movement: {
    id: 'apt_lateral_movement',
    name: 'APT Kill Chain',
    description:
      'Advanced persistent threat exploited web-01 vulnerability, pivoting through the network. Full kill chain: initial access, lateral movement, privilege escalation, data exfiltration.',
    difficulty: 'hard',
    maxSteps: 35,
    adversaryBehavior: 'evasive',
    mitreTechniques: ['T1190', 'T1021.002', 'T1003.001', 'T1041'],
    threatCount: 4,
    falsePositiveCount: 2,
    initialCompromisedNodes: ['web-01'],
    attackPhases: [
      makePhase(
        'apt-01', 'Initial Exploitation',
        'Exploited CVE-2024-1234 on web-01 nginx',
        'web-01', 'intrusion', 4, 'T1190',
        'Exploit Public-Facing Application', 'initial-access',
        '91.219.236.166',
      ),
      makePhase(
        'apt-02', 'Lateral to DC',
        'Moving from web-01 to dc-01 via SMB',
        'dc-01', 'lateral_movement', 8, 'T1021.002',
        'SMB/Windows Admin Shares', 'lateral-movement',
        '10.0.2.1',
      ),
      makePhase(
        'apt-03', 'Credential Dump',
        'Dumping LSASS memory on dc-01',
        'dc-01', 'privilege_escalation', 6, 'T1003.001',
        'LSASS Memory', 'credential-access',
        '10.0.1.1',
      ),
      makePhase(
        'apt-04', 'Data Exfiltration',
        'Exfiltrating data from db-01 via C2 channel',
        'db-01', 'exfiltration', 10, 'T1041',
        'Exfiltration Over C2 Channel', 'exfiltration',
        '91.219.236.166', 'exfiltrated',
      ),
    ],
    alerts: [
      makeAlert(
        'ALT-0001', 'critical', 'intrusion',
        'Web Server Exploitation Detected',
        '91.219.236.166', 'web-01',
        'CVE-2024-1234 exploit attempt on nginx.',
        false,
        'Successful exploitation of CVE-2024-1234 on nginx. Webshell uploaded to /tmp/.cache/shell.php. Reverse shell established to 91.219.236.166:443. APT-level tradecraft.',
        'T1190', 0.99,
      ),
      makeAlert(
        'ALT-0002', 'high', 'lateral_movement',
        'Suspicious SMB Activity',
        '10.0.2.1', 'dc-01',
        'web-01 making unusual SMB connections to domain controller.',
        false,
        'Unauthorized SMB connection from web-01 (10.0.2.1) to dc-01 using admin credentials. PsExec-like behavior detected. Lateral movement confirmed.',
        'T1021.002', 0.93,
      ),
      makeAlert(
        'ALT-0003', 'critical', 'privilege_escalation',
        'LSASS Memory Access',
        '10.0.1.1', 'dc-01',
        'Process accessing LSASS memory on domain controller.',
        false,
        'Mimikatz-style LSASS dump detected on dc-01. Process "lsass_dump.exe" accessing protected memory. Domain admin credentials likely compromised.',
        'T1003.001', 0.97,
      ),
      makeAlert(
        'ALT-0004', 'high', 'exfiltration',
        'Large Data Transfer to External IP',
        '10.0.3.1', 'db-01',
        'Database server sending large volume to external IP.',
        false,
        'db-01 transferring 2.3GB to 91.219.236.166 over encrypted channel. Data matches production database export format. Active exfiltration in progress.',
        'T1041', 0.96,
      ),
      makeAlert(
        'ALT-0005', 'low', 'anomalous_traffic',
        'DNS Query Spike',
        '10.0.1.1', 'dc-01',
        'Increased DNS queries from domain controller.',
        true,
        'Benign. Scheduled Active Directory replication causing DNS query spike. Matches expected AD sync window. Normal operational behavior.',
        '', 0.2,
      ),
      makeAlert(
        'ALT-0006', 'low', 'anomalous_traffic',
        'Workstation Update Traffic',
        '10.0.4.3', 'ws-03',
        'Windows Update downloading patches.',
        true,
        'Benign. Windows Update downloading monthly security patches. Expected Patch Tuesday activity. No indicators of compromise.',
        '', 0.08,
      ),
    ],
    falsePositiveAlerts: [],
  },

  ransomware_outbreak: {
    id: 'ransomware_outbreak',
    name: 'Ransomware Outbreak',
    description:
      'Ransomware hit ws-01 via phishing. Spreading laterally via SMB, encrypting workstations. Protect the backup server. Time is critical.',
    difficulty: 'hard',
    maxSteps: 20,
    adversaryBehavior: 'persistent',
    mitreTechniques: ['T1566.001', 'T1486', 'T1021.002', 'T1490'],
    threatCount: 4,
    falsePositiveCount: 1,
    initialCompromisedNodes: ['ws-01'],
    attackPhases: [
      makePhase(
        'ransom-01', 'Patient Zero Infection',
        'ws-01 infected via phishing email with ransomware payload',
        'ws-01', 'ransomware', 3, 'T1566.001',
        'Spearphishing Attachment', 'initial-access',
        '45.155.205.233', 'encrypted',
      ),
      makePhase(
        'ransom-02', 'Lateral Spread to ws-02',
        'Ransomware spreading via SMB to ws-02',
        'ws-02', 'lateral_movement', 5, 'T1021.002',
        'SMB/Windows Admin Shares', 'lateral-movement',
        '10.0.4.1', 'encrypted',
      ),
      makePhase(
        'ransom-03', 'Lateral Spread to ws-03',
        'Ransomware spreading via SMB to ws-03',
        'ws-03', 'ransomware', 7, 'T1486',
        'Data Encrypted for Impact', 'impact',
        '10.0.4.1', 'encrypted',
      ),
      makePhase(
        'ransom-04', 'Backup Destruction',
        'Attempting to encrypt/destroy backup server',
        'backup-01', 'ransomware', 12, 'T1490',
        'Inhibit System Recovery', 'impact',
        '10.0.4.1', 'encrypted',
      ),
    ],
    alerts: [
      makeAlert(
        'ALT-0001', 'critical', 'ransomware',
        'Ransomware Detected on Workstation',
        '45.155.205.233', 'ws-01',
        'File encryption activity detected on ws-01.',
        false,
        'Ransomware payload executing on ws-01. Files being encrypted with .locked extension. Ransom note dropped. C2 callback to 45.155.205.233. Immediate isolation required.',
        'T1486', 0.99,
      ),
      makeAlert(
        'ALT-0002', 'high', 'lateral_movement',
        'SMB Propagation Attempt',
        '10.0.4.1', 'ws-02',
        'ws-01 attempting to spread via SMB.',
        false,
        'ws-01 scanning internal SMB shares. Copying encrypted payload to ws-02 via admin$ share. Using harvested domain credentials. Ransomware lateral movement.',
        'T1021.002', 0.94,
      ),
      makeAlert(
        'ALT-0003', 'critical', 'ransomware',
        'Backup Server Access Attempt',
        '10.0.4.1', 'backup-01',
        'Ransomware attempting to reach backup infrastructure.',
        false,
        'Connection attempts from compromised workstation segment to backup-01. Trying to delete shadow copies and encrypt backup volumes. If successful, recovery will be impossible.',
        'T1490', 0.97,
      ),
      makeAlert(
        'ALT-0004', 'low', 'anomalous_traffic',
        'Antivirus Definition Update',
        '10.0.4.2', 'ws-02',
        'AV engine downloading updated signatures.',
        true,
        'Benign. Windows Defender downloading latest signature updates. Standard daily update schedule. No malicious indicators.',
        '', 0.05,
      ),
    ],
    falsePositiveAlerts: [],
  },

  supply_chain_compromise: {
    id: 'supply_chain_compromise',
    name: 'Supply Chain Attack',
    description:
      'Trojanized software update deployed to app-01. Backdoor establishing C2, staging credentials, preparing for data exfiltration from db-01.',
    difficulty: 'hard',
    maxSteps: 30,
    adversaryBehavior: 'evasive',
    mitreTechniques: ['T1195.002', 'T1059.001', 'T1003.001', 'T1074.001', 'T1041'],
    threatCount: 4,
    falsePositiveCount: 2,
    initialCompromisedNodes: ['app-01'],
    attackPhases: [
      makePhase(
        'supply-01', 'Trojanized Update',
        'Malicious code in app-01 software update',
        'app-01', 'intrusion', 4, 'T1195.002',
        'Supply Chain Compromise: Software Supply Chain', 'initial-access',
        '198.51.100.88',
      ),
      makePhase(
        'supply-02', 'C2 Establishment',
        'Backdoor establishing command and control channel',
        'app-01', 'anomalous_traffic', 6, 'T1059.001',
        'PowerShell', 'execution',
        '198.51.100.88',
      ),
      makePhase(
        'supply-03', 'Credential Harvesting',
        'Harvesting credentials from app-01 config files and memory',
        'dc-01', 'privilege_escalation', 8, 'T1003.001',
        'LSASS Memory', 'credential-access',
        '10.0.3.2',
      ),
      makePhase(
        'supply-04', 'Data Exfiltration',
        'Exfiltrating data from db-01 through app-01 C2',
        'db-01', 'exfiltration', 10, 'T1041',
        'Exfiltration Over C2 Channel', 'exfiltration',
        '198.51.100.88', 'exfiltrated',
      ),
    ],
    alerts: [
      makeAlert(
        'ALT-0001', 'high', 'intrusion',
        'Suspicious Process After Update',
        '198.51.100.88', 'app-01',
        'New process spawned after recent software update.',
        false,
        'Process "java_update_svc.exe" spawned post-update. Not in original package manifest. Connecting to 198.51.100.88 on port 443. Supply chain compromise suspected.',
        'T1195.002', 0.88,
      ),
      makeAlert(
        'ALT-0002', 'medium', 'anomalous_traffic',
        'Encoded PowerShell Commands',
        '10.0.3.2', 'app-01',
        'Base64-encoded PowerShell execution detected.',
        false,
        'PowerShell executing encoded commands on app-01. Decoded: downloading secondary payload from C2 server. Establishing persistence via scheduled task.',
        'T1059.001', 0.85,
      ),
      makeAlert(
        'ALT-0003', 'high', 'exfiltration',
        'Database Query Anomaly',
        '10.0.3.2', 'db-01',
        'Unusual bulk query pattern from app-01 to database.',
        false,
        'app-01 executing SELECT * across multiple tables. Data being staged in /tmp before exfil. Query pattern inconsistent with normal application behavior.',
        'T1074.001', 0.91,
      ),
      makeAlert(
        'ALT-0004', 'low', 'anomalous_traffic',
        'SSL Certificate Renewal',
        '10.0.3.2', 'app-01',
        'Let\'s Encrypt certificate renewal traffic.',
        true,
        'Benign. Automated Let\'s Encrypt certificate renewal via certbot. Standard 90-day renewal cycle. Destination is legitimate ACME server.',
        '', 0.1,
      ),
      makeAlert(
        'ALT-0005', 'low', 'anomalous_traffic',
        'Log Rotation Activity',
        '10.0.3.1', 'db-01',
        'Logrotate generating large disk I/O.',
        true,
        'Benign. Scheduled logrotate compressing and archiving PostgreSQL transaction logs. Expected weekly maintenance window.',
        '', 0.08,
      ),
    ],
    falsePositiveAlerts: [],
  },

  insider_threat_apt: {
    id: 'insider_threat_apt',
    name: 'Insider + External APT',
    description:
      'Dual simultaneous threat: an insider on ws-04 exfiltrating data to cloud storage, while an external APT compromised mail-01 and is pivoting to dc-01. Maximum difficulty.',
    difficulty: 'nightmare',
    maxSteps: 45,
    adversaryBehavior: 'adaptive',
    mitreTechniques: ['T1078.002', 'T1567.002', 'T1190', 'T1003.001', 'T1021.002', 'T1041'],
    threatCount: 5,
    falsePositiveCount: 3,
    initialCompromisedNodes: ['mail-01'],
    attackPhases: [
      // insider thread
      makePhase(
        'insider-01', 'Insider Data Staging',
        'Malicious insider on ws-04 staging sensitive files',
        'ws-04', 'exfiltration', 8, 'T1078.002',
        'Valid Accounts: Domain Accounts', 'privilege-escalation',
        '10.0.4.4',
      ),
      makePhase(
        'insider-02', 'Cloud Exfiltration',
        'Insider uploading staged data to personal cloud storage',
        'ws-04', 'exfiltration', 12, 'T1567.002',
        'Exfiltration to Cloud Storage', 'exfiltration',
        '10.0.4.4', 'exfiltrated',
      ),
      // external apt thread
      makePhase(
        'apt-01', 'Mail Server Compromise',
        'External attacker exploited mail-01 via spearphishing',
        'mail-01', 'intrusion', 5, 'T1190',
        'Exploit Public-Facing Application', 'initial-access',
        '203.0.113.45',
      ),
      makePhase(
        'apt-02', 'Pivot to DC',
        'APT moving from mail-01 to dc-01',
        'dc-01', 'lateral_movement', 10, 'T1021.002',
        'SMB/Windows Admin Shares', 'lateral-movement',
        '10.0.2.2',
      ),
      makePhase(
        'apt-03', 'DC Credential Dump',
        'APT dumping credentials from domain controller',
        'dc-01', 'privilege_escalation', 8, 'T1003.001',
        'LSASS Memory', 'credential-access',
        '10.0.1.1',
      ),
    ],
    alerts: [
      makeAlert(
        'ALT-0001', 'high', 'exfiltration',
        'Cloud Storage Upload Detected',
        '10.0.4.4', 'ws-04',
        'Large upload to external cloud storage service.',
        false,
        'ws-04 uploading 1.8GB to personal Dropbox account. Files match sensitive HR and financial documents. Upload occurring outside business hours. Insider threat indicators.',
        'T1567.002', 0.87,
      ),
      makeAlert(
        'ALT-0002', 'critical', 'intrusion',
        'Mail Server Compromise',
        '203.0.113.45', 'mail-01',
        'Exploitation detected on mail server.',
        false,
        'Webshell detected on mail-01 at /var/www/owa/.hidden/cmd.aspx. C2 beacon to 203.0.113.45. Attacker has root access. APT-level TTPs observed.',
        'T1190', 0.96,
      ),
      makeAlert(
        'ALT-0003', 'high', 'lateral_movement',
        'Internal Pivot Attempt',
        '10.0.2.2', 'dc-01',
        'mail-01 making suspicious connections to domain controller.',
        false,
        'mail-01 using Pass-the-Hash to authenticate to dc-01 SMB. Copying reconnaissance tools. Lateral movement from initial foothold to high-value target.',
        'T1021.002', 0.93,
      ),
      makeAlert(
        'ALT-0004', 'critical', 'privilege_escalation',
        'Domain Admin Credential Theft',
        '10.0.1.1', 'dc-01',
        'LSASS memory dump on domain controller.',
        false,
        'Mimikatz detected on dc-01. Successfully dumped 14 domain admin password hashes. Attacker now has full domain control. Immediate containment required.',
        'T1003.001', 0.99,
      ),
      makeAlert(
        'ALT-0005', 'medium', 'anomalous_traffic',
        'VPN Connection from Executive',
        '10.0.4.4', 'ws-04',
        'Executive workstation establishing VPN tunnel.',
        true,
        'Benign. Executive connecting to corporate VPN from home office. Certificate-based auth. Matches known device fingerprint and expected usage pattern.',
        '', 0.25,
      ),
      makeAlert(
        'ALT-0006', 'low', 'anomalous_traffic',
        'Print Spooler Activity',
        '10.0.4.3', 'ws-03',
        'Unusual print spooler service restart.',
        true,
        'Benign. Print spooler auto-restarted after driver update. Windows event log confirms legitimate driver installation from IT-approved package.',
        '', 0.1,
      ),
      makeAlert(
        'ALT-0007', 'low', 'anomalous_traffic',
        'LDAP Query Volume',
        '10.0.1.1', 'dc-01',
        'High volume of LDAP queries.',
        true,
        'Benign. Azure AD Connect synchronization running scheduled delta sync. Matches expected connector configuration and sync window.',
        '', 0.15,
      ),
    ],
    falsePositiveAlerts: [],
  },
};

// ordered list for auto-demo cycling
export const SCENARIO_ORDER = [
  'script_kiddie',
  'phishing_campaign',
  'apt_lateral_movement',
  'ransomware_outbreak',
  'supply_chain_compromise',
  'insider_threat_apt',
] as const;

export function getScenario(id: string): ScenarioConfig | undefined {
  return SCENARIOS[id];
}
